title: Falk Kyburz
author:
  name: Falk Kyburz
  email: falkkyburz@proton.me
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

email: falkkyburz@proton.me

github_username:  falkkyburz
linkedin_username: falkkyburz

url: "falkkyburz.com"
baseurl: ""
permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - cv.md

remote_theme: jekyll/minima # https://github.com/jekyll/minima
excerpt_separator: "<!--more-->"
show_excerpts: true

minima:
  skin: dark
  date_format: "%Y-%m-%d"
  social_links:
    - { platform: github,   user_url: "https://github.com/falkkyburz" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/falkkyburz" }
